name: 'MeshMap-Snapshot'
description: 'Walks in application and takes a shot of your infrastructure using Meshery Extension MeshMap'
author: Layer5
inputs:
  designId:  # id of input
    description: 'Give the Design Id'
    required: false
    default: '{}'
  applicationId:
    description: "Give the application Id"
    required: false
  githubToken:
    description: "Github token"
    required: false
  providerToken:
    description: "Meshery Authentication Provider Token"
    required: true
  cypressRecordKey:
    description: "cypress record key"
    required: false
  prNumber:
    description: "The Pull request on which comment has to be made"
    required: false
    default: 0
  filePath: 
    description: "the relative filepath of the location where the manifests are stored"
    required: false
    
outputs:
  mardownResult: # id of output
    description: 'The markdown result'
runs:
  using: "composite"
  steps:
    - name: ping playground
      id: ping-playground
      run: |
        echo "IS_PLAYGROUND_RUNNING=$( echo $(./action/playground-ping.sh))" >> "$GITHUB_OUTPUT"
      shell: bash
    - run: echo $IS_PLAYGROUND_RUNNING
      shell: bash
    - name: set active cluster URL as playground
      if: ${{ steps.ping-playground.outputs.IS_PLAYGROUND_RUNNING }}
      run: echo "MESHERY_URL=https://playground.meshery.io" >> $GITHUB_ENV
      shell: bash
    - name: set active cluster URL as localhost:9081
      if: ${{ !steps.ping-playground.outputs.IS_PLAYGROUND_RUNNING }}
      run: echo "MESHERY_URL=http://127.0.0.1:9081" >> $GITHUB_ENV
      shell: bash
    - name: Create k8s Kind Cluster
      if: ${{ !steps.ping-playground.outputs.IS_PLAYGROUND_RUNNING }}
      uses: helm/kind-action@v1.7.0
      with:
        cluster_name: "kind-cluster"
    - run: echo ${{ steps.ping-playground.outputs.IS_PLAYGROUND_RUNNING }}
      shell: bash
    - run: 
      working-directory: action/cypress-action/
      if: ${{ !steps.ping-playground.outputs.IS_PLAYGROUND_RUNNING }}
      shell: bash
    - run: FILE_PATH=${{ inputs.filePath }} ./action/manifest-merger.sh # creates file in root dir
      shell: bash
    # - run: mv __intermediate_file.yml action/cypress-action/cypress/fixtures/__intermediate_file.yml
    #   shell: bash That was needed if the curl approach wasn't working
    # - run: ls && echo "APPLICATION_ID=$(MESHERY_SERVER_BASE_URL=$MESHERY_URL UPLOAD_TYPE='Kubernetes Manifest' PROVIDER_TOKEN=${{ inputs.providerToken }}  ./action/uploadApplication.sh) >> "$GITHUB_OUTPUT" 
      # shell: bash
    - run: "APPLICATION_ID=$(MESHERY_SERVER_BASE_URL="https://playground.meshery.io" UPLOAD_TYPE='Kubernetes Manifest' PROVIDER_TOKEN=${{ inputs.providerToken }}  ./action/uploadApplication.sh)" >> $GITHUB_ENV
      shell: bash
    - run: echo $APPLICATION_ID && echo ${{env.APPLICATION_ID}}
      shell: bash
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        working-directory: action/cypress-action
        spec: cypress/e2e/e2e/**/*
        browser: chrome 
        # record: true
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
        CYPRESS_token: ${{ inputs.providerToken }}
        CYPRESS_releasetag: ${{env.tag}}
        CYPRESS_applicationId: ${{ env.APPLICATION_ID }}
        # CYPRESS_RECORD_KEY: ${{ inputs.cypressRecordKey }}
    - run: ls
      shell: bash
    - run: tree action/cypress-action/cypress/ -L 2me
      shell: bash
    - name: Upload Cypress artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-ss
        path: action/cypress-action/cypress/videos
    - name: Upload Cypress artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-ss
        path: action/cypress-action/cypress/screenshots
    - run:  echo "SCREENSHOT_NAME=$(ls)" >> $GITHUB_ENV # Assumption: There is only one screenshot in the download directory
      working-directory: action/cypress-action/cypress/downloads
      shell: bash
    - run: mv "$SCREENSHOT_NAME" screenshot.png
      working-directory: action/cypress-action/cypress/downloads
      shell: bash
    - run: |
        export request=$(curl --fail -d "$(base64 -i screenshot.png)" 'https://meshery.layer5.io/api/integration/github/meta/artifacts' \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Bearer ${{ inputs.providerToken }}");
        # TODO: fail in case of not 2XX or 3XX
        echo "RESOURCE_URL=$request" >> $GITHUB_ENV
      id: cloud-response
      working-directory: action/cypress-action/cypress/downloads
      shell: bash
    - name: Get Organization and Repository
      if: always()
      run: |
        # Extract organization and repository names from GITHUB_REPOSITORY
        IFS='/' read -r -a repoArray <<< "$GITHUB_REPOSITORY"
        organization=${repoArray[0]}
        repository=${repoArray[1]}

        echo "ORGANIZATION=$organization" >> $GITHUB_ENV
        echo "REPOSITORY=$repository" >> $GITHUB_ENV
      shell: bash
    - run: echo $ORGANIZATION && echo $REPOSITORY && echo $PR_NUM
      shell: bash
    - name: Comment Success Status
      if: ${{ success() && inputs.prNumber != '0' }}
      uses: hasura/comment-progress@v2.1.0
      with:
        github-token: ${{ inputs.githubToken }}
        repository: "${{env.ORGANIZATION}}/${{env.REPOSITORY}}"
        number: ${{ inputs.prNumber }}
        id: meshmap-snapshot
        message: '[<img src="${{env.RESOURCE_URL}}">](https://meshery.layer5.io/catalog/applications)'
        append: false




# TODOS:
# Manage wrong file-path
# Manage curl Failure