name: "MeshMap-Snapshot"
description: "Walks in application and takes a shot of your infrastructure using Meshery Extension MeshMap"
author: Layer5
inputs:
  designId: # id of input  #deprecated
    description: "The design uuid, example: 3c116d0a-49ea-4294-addc-d9ab34210662"
    required: false
    default: "{}"
  applicationId: #deprecated
    description: "The application uuid, example: 3c116d0a-49ea-4294-addc-d9ab34210662"
    required: false
  githubToken:
    description: "Github PAT token"
    required: true
  providerToken:
    description: "Meshery Authentication Provider Token"
    required: true
  prNumber:
    description: "The Pull request on which comment has to be made"
    required: false
    default: 0
  filePath:
    description: "The relative filepath of the location where the manifests are stored"
    required: false
  application_type:
    description: "Application upload type, any of the three, Kubernetes Manifest, Docker Compose, Helm Chart"
    required: true
  application_url:
    description: "Application's source url where the manifests or data is stored"
    required: false
outputs:
  mardownResult: # id of output
    description: "The markdown result"
runs:
  using: "composite"
  steps:
    - name: ping playground
      id: ping-playground
      run: |
        echo "IS_PLAYGROUND_RUNNING=$( echo $(./action/playground-ping.sh))" >> "$GITHUB_OUTPUT"
      shell: bash
    - run: echo $IS_PLAYGROUND_RUNNING
      shell: bash
    - name: set active cluster URL as playground
      if: ${{ steps.ping-playground.outputs.IS_PLAYGROUND_RUNNING }}
      run: echo "MESHERY_URL=https://playground.meshery.io" >> $GITHUB_ENV
      shell: bash
    - name: set active cluster URL as localhost:9081
      if: ${{ !steps.ping-playground.outputs.IS_PLAYGROUND_RUNNING }}
      run: echo "MESHERY_URL=http://127.0.0.1:9081" >> $GITHUB_ENV
      shell: bash
    - name: Create k8s Kind Cluster
      if: ${{ !steps.ping-playground.outputs.IS_PLAYGROUND_RUNNING }}
      uses: helm/kind-action@v1.7.0
      with:
        cluster_name: "kind-cluster"
    - run: echo ${{ steps.ping-playground.outputs.IS_PLAYGROUND_RUNNING }}
      shell: bash
    - run:
      working-directory: action/cypress-action/
      if: ${{ !steps.ping-playground.outputs.IS_PLAYGROUND_RUNNING }}
      shell: bash
    - run: FILE_PATH=${{ inputs.filePath }} ./action/manifest-merger.sh # creates file in root dir
      if: ${{ !inputs.application_url }}
      shell: bash
    - run: |
        AppId=$(MESHERY_SERVER_BASE_URL="https://playground.meshery.io" UPLOAD_TYPE="${{inputs.application_type}}" PROVIDER_TOKEN=${{ inputs.providerToken }}  ./action/uploadApplicationFile.sh)
        echo $AppId
        echo "APPLICATION_ID=$AppId" >> $GITHUB_ENV
      if: ${{ !inputs.application_url }}
      shell: bash
    - run: |
        AppId=$(MESHERY_SERVER_BASE_URL="https://playground.meshery.io" UPLOAD_TYPE="${{inputs.application_type}}" PROVIDER_TOKEN=${{ inputs.providerToken }} UPLOAD_URL=${{ inputs.application_url }}  ./action/uploadApplicationUrl.sh)
        echo $AppId
        echo "APPLICATION_ID=$AppId" >> $GITHUB_ENV
      if: ${{ inputs.application_url }}
      shell: bash
    - run: echo $APPLICATION_ID && echo ${{env.APPLICATION_ID}}
      shell: bash
    - name: Cypress run
      uses: action/cypress-job #reference to cypress workflow
    - run: ls
      shell: bash
    - run: tree action/cypress-action/cypress/ -L 2me
      shell: bash
    - name: Upload Cypress artifacts
      uses: cypress-ss
    - name: Upload Cypress artifacts
      uses: cypress-artifacts
    - run: echo "SCREENSHOT_NAME=$(ls)" >> $GITHUB_ENV # Assumption: There is only one screenshot in the download directory
      working-directory: action/cypress-action/cypress/downloads
      shell: bash
    - run: mv "$SCREENSHOT_NAME" screenshot.png
      working-directory: action/cypress-action/cypress/downloads
      shell: bash
    - run: node --version
      shell: bash
    - run: npm ci
      working-directory: action/node-file-upload
      shell: bash
    - run: ./token-provider.sh
      working-directory: action/
      shell: bash
    - name: Comment Success Status
      if: ${{ success() && inputs.prNumber != '0' && env.RESOURCE_URL != false }}
      uses: hasura/comment-progress@v2.2.0
      with:
        github-token: ${{ inputs.githubToken }}
        repository: ${{github.repository}}
        number: ${{ inputs.prNumber }}
        id: meshmap-snapshot
        message: '[<img src="${{env.RESOURCE_URL}}">](https://meshery.layer5.io/catalog/content/applications)'
        append: false
