name: 'Infra-shot'
description: 'Walks in application and takes a shot of your infrastructure using Meshery Extension MeshMap'
author: Layer5
inputs:
  designId:  # id of input
    description: 'Give the Design Id'
    required: false
    default: '{}'
  applicationId:
    description: "Give the application Id"
    required: false
outputs:
  mardownResult: # id of output
    description: 'The markdown result'
runs:
  using: "composite"
  steps:
    - run: 
      shell: bash
    - name: ping playground
      id: ping-playground
      run: |
        echo "IS_PLAYGROUND_RUNNING=$(./playground-ping.sh)" >> "$GITHUB_OUTPUT"
      shell: bash
    - run: echo ${{ steps.ping-playground.outputs.IS_PLAYGROUND_RUNNING }}
      shell: bash
    - run: 
    - run: docker ps
      shell: bash
    - run: ping localhost -p 9081 -c 8
      shell: bash
