name: 'Infra-shot'
description: 'Walks in application and takes a shot of your infrastructure using Meshery Extension MeshMap'
author: Layer5
inputs:
  designId:  # id of input
    description: 'Give the Design Id'
    required: false
    default: '{}'
  applicationId:
    description: "Give the application Id"
    required: false
outputs:
  mardownResult: # id of output
    description: 'The markdown result'
runs:
  using: 'composite'
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash