name: 'cypress-test-sumary'
description: 'Cypress test summary table'
author: Layer5
inputs:
  jsonInput:  # id of input
    description: 'Test output in json'
    required: true
    default: {}
outputs:
  mardownResult: # id of output
    description: 'The markdown result'
runs:
  using: 'node16'
  main: 'dist/index.js'
