name: 'Infra-shot'
description: 'Walks in application and takes a shot of your infrastructure using Meshery Extension MeshMap'
author: Layer5
inputs:
  designId:  # id of input
    description: 'Give the Design Id'
    required: false
    default: '{}'
  applicationId:
    description: "Give the application Id"
    required: false
outputs:
  mardownResult: # id of output
    description: 'The markdown result'
runs:
  using: "composite"
  steps:
    - run: curl -L https://meshery.io/install | ADAPTERS=istio PLATFORM=docker bash -
      shell: bash
    - run: sleep 10
      shell: bash
    - run: docker ps
      shell: bash
    - run: ping localhost -p 9081 -c 8
      shell: bash
