name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node pkges
        working-directory: node-action
        run: npm install
      - name: build
        working-directory: node-action
        run: |
          NODE_OPTIONS=--openssl-legacy-provider npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: test_result
        uses: ./
        with:
          designId: ${{ secrets.TEST_SECRET }} #works
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          providerToken: ${{ secrets.PROVIDER_TOKEN }}
          cypressRecordKey: ${{ secrets.CYPRESS_RECORD_KEY }}
          

