name: 'JSON e2e test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          path: './'
      - run: |
          echo 'OUTPUT<<EOF' >> $GITHUB_ENV
          cat ./__tests__/output.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name:  show output
        run: echo ${{env.OUTPUT}}
      - id: test_result
        name: "Run Test on the output.json"
        uses: ./
        with: ${{env.OUTPUT}}
      