name: 'JSON e2e test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls .
          # echo 'OUTPUT<<EOF' >> $GITHUB_ENV
          # cat ./__tests__/output.json >> $GITHUB_ENV
          # echo 'EOF' >> $GITHUB_ENV
      - name:  show output
        run: echo ${{fromJson(env.OUTPUT)}}